### ISSUE TITLE
varchar(n) being treated as JSONB

### ISSUE THREAD

**Issue by bh2smith** [bh2smith/dune-sync#106]
Got this:

```
[WARNING] dune-sync:dune._handle_column_types:131 - Unknown column: varchar(7) - treating as JSONB
```

For this config:

```
  - name: cow-solvers
    source:
      ref: Dune
      query_id: 4345829
      query_engine: medium
      poll_frequency: 1
    destination:
      ref: PG
      table_name: solvers
      if_exists: replace
```

We should be able to handle these as regular varchar.
