### ISSUE TITLE
Add option for custom dune request timeout 

### ISSUE THREAD

**Issue by bram-vdberg** [bh2smith/dune-sync#121]
In dune sync v1 we add an option to set a [custom timeout for the DuneClient](https://github.com/cowprotocol/dune-sync/blob/64468b6c25fafe80150ddc3195dbe75f26ebc53b/src/main.py#L57). This allows us to increase the timeout from 10 seconds to a larger value when we want to upload large files.

For uploading larger files we would want to add a similar configuration parameter to increase the timeout for the DuneClient that we can pass as a parameter in the job's config file.

```
destination:
      ref: Dune
      table_name: dune_sync_test_table
      timeout: 10
```
