### ISSUE TITLE
src.config.RuntimeConfig.validate throws bogus warnings

### ISSUE THREAD

**Issue by mooster531** [bh2smith/dune-sync#34]
1. Have this `config.toml`:

```toml
[[jobs]]
source = "dune"
destination = "postgres"
table_name = "results_123"
query_id = 1
poll_frequency = 1
query_engine = "medium"


[[jobs]]
source = "postgres"
destination = "dune"
table_name = "dune_destination_table"
query_string = "SELECT * FROM results_123"
```

2. Have it loaded into the program: 
```python
RuntimeConfig.load_from_toml("config.toml")
```

3. Observe the logs:
```
WARNING:dune-sync:Detected multiple jobs running the same query
WARNING:dune-sync:Detected multiple jobs writing to the same table
```

Root cause:
```
        if len(self.dune_to_local_jobs) == len(
            set(j.query_id for j in self.dune_to_local_jobs)
        ):
            log.warning("Detected multiple jobs running the same query")
        if len(self.local_to_dune_jobs) == len(
            set(j.table_name for j in self.local_to_dune_jobs)
        ):
            log.warning("Detected multiple jobs writing to the same table")
```

The set of "dune jobs" running for the same query will always be equal to the set of "dune jobs" if dune jobs == 1. The same applies for the table destination check.
