### ISSUE TITLE
PostgresSource: Support for both sql files OR query strings

### ISSUE THREAD

**Issue by bh2smith** [bh2smith/dune-sync#44]
We might want to make it possible to run a query file. I suspect some queries might be very long strings. In this case, the user would have to mount the config file along with, say a directory "queries" containing a bunch of raw SQL.

_Originally posted by @bh2smith in https://github.com/bh2smith/dune-sync/pull/43#discussion_r1828791499_

**Comment by mooster531** [comment]
Query file could be supported but we might also suggest using Yaml Heredoc syntax for that, like this:
```yaml
  - name: Write Results of Job 1 back
    source:
      ref: postgres
      if_exists: "append"
      query_string: |
        this
        will
        be
        some
        very
        long
        query

    destination:
      ref: dune
      table_name: "dune_sync_test_table"
```
