### ISSUE TITLE
Multiple PG Instances

### ISSUE THREAD

**Issue by bh2smith** [bh2smith/dune-sync#45]
Just a thought, I wonder if the end user might have multiple postgres instances. Maybe we could do something like...

`DB_URL_*`

and then the config could reference which to use by number?

Open to suggestions.

_Originally posted by @bh2smith in https://github.com/bh2smith/dune-sync/pull/43#discussion_r1828794922_

**Comment by mooster531** [comment]
I'd rather just have the DSN as a parameter in the `source` / `destination` blocks, like:
```yaml
    destination:
      ref: postgres
      table_name: "test_table"
      if_exists: "replace"
      dsn: "postgresql://postgres:postgres@localhost:5672/dbname"

```

**Comment by bh2smith** [comment]
> I'd rather just have the DSN as a parameter in the source / destination blocks, like:

Wouldn't this expose a secret in a config file?

**Comment by mooster531** [comment]
> > I'd rather just have the DSN as a parameter in the source / destination blocks, like:
> 
> Wouldn't this expose a secret in a config file?

Technically yes, but the config is property of the user and should only exist on their secure environment. Still, we can think of a way to handle multiple environment variables. I'd just prefer to have them named.

- We can consider allowing sources and destinations to be named:
```yaml
destination:
      ref: postgres
      table_name: "test_table"
      if_exists: "replace"
      dsn: "postgresql://postgres:postgres@localhost:5672/dbname"
      name: "my_postgres"
```

Then look up an env var called `DUNE_SYNC_MY_POSTGRES_DSN`. Or something along those lines.
