### ISSUE TITLE
Multiple Sources & Destinations in a Single Config

### ISSUE THREAD

**Issue by bh2smith** [bh2smith/dune-sync#55]
In order to support multiple sources and destinations without redundancy. Our YAML should look something like this:

```yaml
sources:
  - name: Dune1
    type: dune
    key: ${DUNE_API_KEY_1}
  - name: PG1
    type: postgres
    key: ${PG_KEY_1}
  - name: PG2
    type: postgres
    key: ${PG_KEY_2}

destinations:
  - name: Dune1
    type: dune
    key: ${DUNE_API_KEY_2}
  - name: PG1
    type: postgres
    key: ${PG_KEY_1}

jobs:
  - name: Sync Parameterized Dune Query with Multiple Types to Postgres
    source:
      ref: Dune1
      query_id: 4238114
      query_engine: medium
      poll_frequency: 5
      parameters:
        - name: blockchain
          value: gnosis
          type: ENUM
        - name: block_time
          value: "2024-09-01 00:00:00"
          type: DATE
        - name: result_limit
          value: "10"
          type: NUMBER
    destination:
      ref: PG1
      table_name: results_4238114
      if_exists: replace

  - name: Table Independent Query to Dune
    source:
      ref: PG1
      if_exists: append
      query_string: "SELECT 1 as number, '\\x1234'::bytea as my_bytes;"
    destination:
      ref: Dune2
      table_name: dune_sync_test_table

  - name: Sync Postgres to Another Postgres Table
    source:
      ref: PG1
      query_string: "SELECT * FROM existing_table"
    destination:
      ref: PG2
      table_name: pg_sync_test_table
      if_exists: append

```

Note that

1. The key reference template indicates that the key should be read from the env vars.
2. While it is unlikely that anyone would have multiple dune keys, a single dune key is linked to a user account and some users have read access to tables that others don't.

Our class structure may have to adapt a bit by decoupling the query information from the database connections. For example Dune1 is a Source, but we might use this connection to "fetch" multiple queries. That is, we may want to reuse a Source for multiple different fetches `DuneSource`. The easy work around for this would be to clone/duplicate the structure and update the query data when using for a new job.
