### ISSUE TITLE
Consider combining source and destination type to single type

### ISSUE THREAD

**Issue by fleupold** [bh2smith/dune-sync#75]
Given that `source` and `destination` fields have exactly the same type it may make sense combining them into one field (e.g. datasources). Otherwise, one will frequently have redundant configurations like:

```yaml
sources:
  - name: Dune
    type: dune
    key: ${DUNE_API_KEY}
  - name: PG
    type: postgres
    key: ${DB_URL}

destinations:
  - name: Dune
    type: dune
    key: ${DUNE_API_KEY}
  - name: PG
    type: postgres
    key: ${DB_URL}
```

instead of a more concise

```yaml
datasources:
  - name: Dune
    type: dune
    key: ${DUNE_API_KEY}
  - name: PG
    type: postgres
    key: ${DB_URL}
```
