### ISSUE TITLE
Unnecessarily strict env var check

### ISSUE THREAD

**Issue by fleupold** [bh2smith/dune-sync#77]
It's in theory possible to use different env vars in the sources or not have e.g. a postgres db at all (ie to mirror between dune accounts).

https://github.com/bh2smith/dune-sync/blob/aac96341fc84850491d518427115fa86f5a32198/src/config.py#L108-L111

I don't think we should be enforcing the existence of certain env variables as this would be a perfectly valid config:

```yaml
sources:
  - name: Dune
    type: dune
    key: ${DUNE_API_KEY}
  - name: PG
    type: postgres
    key: ${READONLY_DB}

destinations:
  - name: Dune
    type: dune
    key: ${DUNE_API_KEY}
```
