### ISSUE TITLE
Allow for env-var substitution inside query_string and table_name

### ISSUE THREAD

**Issue by fleupold** [bh2smith/dune-sync#94]
For some use cases, the exact query string or target table name may differ from run to run (e.g. we are looking to sync all order rewards for the current month into a dune table that is suffixed with the current month).

I don't think it is necessary to support a sophisticated templating syntax for this. 

However, I think it would be nice if I could specify a config like:

```yaml
- name: order_rewards
  source:
   ref: postgres
   query_string: "SELECT * from order_rewards where DATE_TRUNC('month', timestamp) = '${DATE_RANGE}'"
  destination:
    ref: dune
    table_name: order_rewards_${DATE_RANGE}
```

and then if `DATE_RANGE=2024-11-01` in the environment we fetch order rewards from November and upload them into `order_rewards_2024-11-01`
